const commonFilters = {
  status: {
    label: 'Статус',
    key: 'status',
    options: ['active', 'pending_verification', 'blocked', 'disabled', 'created', 'playing', 'finished', 'waiting', 'closed', 'new', 'confirmed', 'failed'],
  },
  mode: {
    label: 'Режим',
    key: 'mode',
    options: ['solo', '1v1', '2v2', '5v5', 'royale'],
  },
  match_type: {
    label: 'Тип матча',
    key: 'match_type',
    options: ['ranked', 'casual', 'friends', 'private'],
  },
}

export const adminResourceConfigs = {
  visits: {
    key: 'visits',
    title: 'Посещения',
    section: 'Обзор',
    path: '/analytics/visits',
    advancedFilters: [
      { key: 'user_id', label: 'User ID', type: 'number', placeholder: 'ID пользователя' },
      { key: 'path', label: 'Страница', type: 'text', placeholder: '/profile' },
      { key: 'source', label: 'Источник', type: 'text', placeholder: 'direct, google...' },
      { key: 'device_type', label: 'Устройство', type: 'select', options: ['desktop', 'mobile', 'tablet', 'bot', 'unknown'] },
      { key: 'occurred_from', label: 'С', type: 'datetime-local' },
      { key: 'occurred_to', label: 'По', type: 'datetime-local' },
    ],
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'user_id', label: 'User ID', type: 'userLink' },
      { key: 'session_key', label: 'Сеанс' },
      { key: 'path', label: 'Страница', type: 'pageLink' },
      { key: 'source', label: 'Источник' },
      { key: 'device_type', label: 'Устройство', type: 'deviceInfo' },
      { key: 'occurred_at', label: 'Время', type: 'datetime' },
    ],
  },
  gameActivity: {
    key: 'gameActivity',
    title: 'Игровая статистика',
    section: 'Обзор',
    path: '/analytics/games',
    filters: [commonFilters.mode, commonFilters.match_type],
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'match_id', label: 'Матч' },
      { key: 'room_id', label: 'Комната' },
      { key: 'mode', label: 'Режим', type: 'badge' },
      { key: 'match_type', label: 'Тип' },
      { key: 'event_type', label: 'Событие', type: 'badge' },
      { key: 'occurred_at', label: 'Время', type: 'datetime' },
    ],
  },
  sessions: {
    key: 'sessions',
    title: 'Онлайн и сеансы',
    section: 'Обзор',
    path: '/sessions',
    advancedFilters: [
      { key: 'user_id', label: 'User ID', type: 'number', placeholder: 'ID пользователя' },
      { key: 'status', label: 'Статус', type: 'select', options: ['active', 'idle', 'ended', 'expired'] },
      { key: 'started_from', label: 'Старт с', type: 'datetime-local' },
      { key: 'started_to', label: 'Старт по', type: 'datetime-local' },
      { key: 'last_seen_from', label: 'Активность с', type: 'datetime-local' },
      { key: 'last_seen_to', label: 'Активность по', type: 'datetime-local' },
    ],
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'user_id', label: 'User ID', type: 'userLink' },
      { key: 'session_key', label: 'Сеанс' },
      { key: 'socket_id', label: 'Socket' },
      { key: 'status', label: 'Статус', type: 'badge' },
      { key: 'started_at', label: 'Старт', type: 'datetime' },
      { key: 'last_seen_at', label: 'Активность', type: 'datetime' },
    ],
  },
  users: {
    key: 'users',
    title: 'Аккаунты',
    section: 'Пользователи',
    path: '/users',
    filters: [commonFilters.status],
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'avatar_url', label: 'Аватар', type: 'avatar', width: '86px' },
      { key: 'username', label: 'Игрок' },
      { key: 'email', label: 'Email' },
      { key: 'status', label: 'Статус', type: 'badge' },
      { key: 'role_id', label: 'Роль' },
      { key: 'created_at', label: 'Создан', type: 'datetime' },
      { key: 'last_login_at', label: 'Последний вход', type: 'datetime' },
    ],
  },
  roles: {
    key: 'roles',
    title: 'Роли',
    section: 'Пользователи',
    path: '/roles',
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'key', label: 'Ключ', type: 'badge' },
      { key: 'name', label: 'Название' },
      { key: 'created_at', label: 'Создана', type: 'datetime' },
    ],
  },
  authLogs: {
    key: 'authLogs',
    title: 'Логи входа',
    section: 'Пользователи',
    path: '/auth/logs',
    advancedFilters: [
      { key: 'id', label: 'ID записи', type: 'number', placeholder: 'Например, 125' },
      { key: 'user_id', label: 'User ID', type: 'number', placeholder: 'ID пользователя' },
      { key: 'event_type', label: 'Событие', type: 'text', placeholder: 'login_success, logout...' },
      { key: 'ip_address', label: 'IP', type: 'text', placeholder: '127.0.0.1' },
      { key: 'created_from', label: 'С', type: 'datetime-local' },
      { key: 'created_to', label: 'По', type: 'datetime-local' },
    ],
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'user_id', label: 'User ID', type: 'userLink' },
      { key: 'event_type', label: 'Событие', type: 'badge' },
      { key: 'ip_address', label: 'IP' },
      { key: 'user_agent', label: 'User Agent', truncate: true },
      { key: 'created_at', label: 'Время', type: 'datetime' },
    ],
  },
  emailVerifications: {
    key: 'emailVerifications',
    title: 'Подтверждение email',
    section: 'Пользователи',
    path: '/email-verifications',
    advancedFilters: [
      { key: 'id', label: 'ID записи', type: 'number', placeholder: 'Например, 54' },
      { key: 'user_id', label: 'User ID', type: 'number', placeholder: 'ID пользователя' },
      { key: 'email', label: 'Email', type: 'email', placeholder: 'player@mail.com' },
      { key: 'status', label: 'Статус', type: 'select', options: ['pending', 'used', 'expired'] },
      { key: 'created_from', label: 'С', type: 'datetime-local' },
      { key: 'created_to', label: 'По', type: 'datetime-local' },
    ],
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'user_id', label: 'User ID', type: 'userLink' },
      { key: 'email', label: 'Email', type: 'userEmailLink' },
      { key: 'status', label: 'Статус', type: 'badge' },
      { key: 'attempts_count', label: 'Попытки', type: 'number' },
      { key: 'expires_at', label: 'Истекает', type: 'datetime' },
      { key: 'verified_at', label: 'Подтвержден', type: 'datetime' },
    ],
  },
  matches: {
    key: 'matches',
    title: 'Матчи',
    section: 'Игры',
    path: '/matches',
    description: 'Журнал матчей: режим, тип, статус, рейтинговость и время создания каждой игры.',
    advancedFilters: [
      { key: 'id', label: 'ID матча', type: 'number', placeholder: 'Например, 240' },
      { key: 'room_id', label: 'Комната', type: 'text', placeholder: 'Room ID' },
      { key: 'mode', label: 'Режим', type: 'select', options: ['solo', '1v1', '2v2', '5v5', 'royale'] },
      { key: 'match_type', label: 'Тип', type: 'select', options: ['ranked', 'casual', 'friends', 'private'] },
      { key: 'status', label: 'Статус', type: 'select', options: ['created', 'playing', 'finished', 'cancelled', 'abandoned'] },
      { key: 'created_from', label: 'С', type: 'datetime-local' },
      { key: 'created_to', label: 'По', type: 'datetime-local' },
    ],
    filters: [commonFilters.mode, commonFilters.match_type, { label: 'Статус', key: 'status', options: ['created', 'playing', 'finished', 'cancelled', 'abandoned'] }],
    columns: [
      { key: 'id', label: 'ID', width: '82px', type: 'matchLink' },
      { key: 'room_id', label: 'Комната' },
      { key: 'mode', label: 'Режим', type: 'badge' },
      { key: 'match_type', label: 'Тип' },
      { key: 'status', label: 'Статус', type: 'badge' },
      { key: 'counts_for_rating', label: 'Рейтинг', type: 'boolean' },
      { key: 'created_at', label: 'Создан', type: 'datetime' },
      { key: 'ended_at', label: 'Завершен', type: 'datetime' },
    ],
  },
  matchTeams: {
    key: 'matchTeams',
    title: 'Команды матчей',
    section: 'Игры',
    path: '/matches/teams',
    description: 'Команды внутри матчей: состав, командный счёт и итог команды.',
    advancedFilters: [
      { key: 'id', label: 'ID команды', type: 'number', placeholder: 'Например, 18' },
      { key: 'match_id', label: 'Матч', type: 'number', placeholder: 'ID матча' },
      { key: 'team_number', label: 'Номер команды', type: 'number', placeholder: '1 или 2' },
      { key: 'result', label: 'Результат', type: 'select', options: ['win', 'lose', 'draw', 'none'] },
      { key: 'created_from', label: 'С', type: 'datetime-local' },
      { key: 'created_to', label: 'По', type: 'datetime-local' },
    ],
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'match_id', label: 'Матч' },
      { key: 'team_number', label: 'Команда' },
      { key: 'team_score', label: 'Счет', type: 'number' },
      { key: 'result', label: 'Результат', type: 'badge' },
      { key: 'created_at', label: 'Создана', type: 'datetime' },
    ],
  },
  matchPlayers: {
    key: 'matchPlayers',
    title: 'Игроки матчей',
    section: 'Игры',
    path: '/matches/players',
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'match_id', label: 'Матч' },
      { key: 'user_id', label: 'User ID', type: 'userLink' },
      { key: 'nickname', label: 'Ник', type: 'userNameLink' },
      { key: 'score', label: 'Счет', type: 'number' },
      { key: 'lines_cleared', label: 'Линии', type: 'number' },
      { key: 'result', label: 'Результат', type: 'badge' },
      { key: 'joined_at', label: 'Вход', type: 'datetime' },
    ],
  },
  matchEvents: {
    key: 'matchEvents',
    title: 'События матчей',
    section: 'Игры',
    path: '/matches/events',
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'match_id', label: 'Матч' },
      { key: 'source_player_id', label: 'Источник' },
      { key: 'target_player_id', label: 'Цель' },
      { key: 'event_type', label: 'Событие', type: 'badge' },
      { key: 'payload', label: 'Payload', type: 'json' },
      { key: 'created_at', label: 'Время', type: 'datetime' },
    ],
  },
  rooms: {
    key: 'rooms',
    title: 'Комнаты',
    section: 'Игры',
    path: '/rooms',
    editable: true,
    statusField: 'status',
    statusOptions: ['waiting', 'playing', 'closed'],
    filters: [{ label: 'Статус', key: 'status', options: ['waiting', 'playing', 'closed'] }, { label: 'Режим', key: 'mode_key', options: ['1v1', '2v2', '5v5', 'royale'] }],
    columns: [
      { key: 'id', label: 'Комната' },
      { key: 'status', label: 'Статус', type: 'inlineStatus' },
      { key: 'match_id', label: 'Матч' },
      { key: 'mode_key', label: 'Режим', type: 'badge' },
      { key: 'owner_user_key', label: 'Владелец' },
      { key: 'updated_at', label: 'Обновлена', type: 'datetime' },
    ],
  },
  gameEffects: {
    key: 'gameEffects',
    title: 'Игровые эффекты',
    section: 'Игры',
    path: '/game/effects',
    description: 'Каталог PvP-эффектов: активность, тексты, иконки, изображения и длительность применения.',
    editable: true,
    statusField: 'status',
    statusOptions: ['active', 'inactive'],
    filters: [{ label: 'Статус', key: 'status', options: ['active', 'inactive'] }],
    advancedFilters: [
      { key: 'effect_key', label: 'Ключ', type: 'text', placeholder: 'darkness' },
      { key: 'status', label: 'Статус', type: 'select', options: ['active', 'inactive'] },
      { key: 'visual', label: 'Визуал', type: 'text', placeholder: 'speed' },
    ],
    editorFields: [
      { key: 'effect_key', label: 'Ключ эффекта', type: 'text', required: true, placeholder: 'new_effect' },
      { key: 'label', label: 'Короткое имя EN', type: 'text', required: true, placeholder: 'Blackout' },
      { key: 'label_ru', label: 'Короткое имя RU', type: 'text', required: true, placeholder: 'Затемнение' },
      { key: 'title', label: 'Название EN', type: 'text', required: true, placeholder: 'Darkness' },
      { key: 'title_ru', label: 'Название RU', type: 'text', required: true, placeholder: 'Тьма' },
      { key: 'description', label: 'Описание EN', type: 'textarea', placeholder: 'What the effect does in battle' },
      { key: 'description_ru', label: 'Описание RU', type: 'textarea', placeholder: 'Что делает эффект в матче' },
      { key: 'icon', label: 'Font Awesome иконка', type: 'text', placeholder: 'fa-moon' },
      { key: 'image_url', label: 'URL картинки', type: 'image', upload: true, placeholder: '/uploads/effects/darkness.webp' },
      { key: 'visual', label: 'Визуальный ключ', type: 'text', defaultValue: 'default', placeholder: 'darkness' },
      { key: 'duration_ms', label: 'Длительность, мс', type: 'number', defaultValue: 4000 },
      { key: 'status', label: 'Статус', type: 'select', options: ['active', 'inactive'], defaultValue: 'active', required: true },
      { key: 'sort_order', label: 'Порядок', type: 'number', defaultValue: 0 },
    ],
    columns: [
      { key: 'image_url', label: 'Картинка', type: 'avatar', width: '86px' },
      { key: 'effect_key', label: 'Ключ', type: 'badge' },
      { key: 'label_ru', label: 'Имя RU' },
      { key: 'title_ru', label: 'Название RU' },
      { key: 'label', label: 'Имя EN' },
      { key: 'title', label: 'Название EN' },
      { key: 'icon', label: 'Иконка', type: 'badge' },
      { key: 'visual', label: 'Визуал', type: 'badge' },
      { key: 'duration_ms', label: 'мс', type: 'number' },
      { key: 'status', label: 'Статус', type: 'inlineStatus' },
      { key: 'sort_order', label: 'Порядок', type: 'number' },
      { key: 'updated_at', label: 'Обновлено', type: 'datetime' },
    ],
  },
  roomPlayers: {
    key: 'roomPlayers',
    title: 'Игроки в комнатах',
    section: 'Игры',
    path: '/rooms/players',
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'room_id', label: 'Комната' },
      { key: 'username', label: 'Игрок' },
      { key: 'is_registered', label: 'Аккаунт', type: 'boolean' },
      { key: 'is_ready', label: 'Готов', type: 'boolean' },
      { key: 'team_number', label: 'Команда' },
      { key: 'updated_at', label: 'Обновлен', type: 'datetime' },
    ],
  },
  rankStats: {
    key: 'rankStats',
    title: 'Текущие ранги',
    section: 'Рейтинг',
    path: '/rating/stats',
    columns: [
      { key: 'avatar_url', label: 'Аватар', type: 'avatar', width: '86px' },
      { key: 'user_id', label: 'User ID', type: 'userLink' },
      { key: 'username', label: 'Ник', type: 'userNameLink' },
      { key: 'rank_points', label: 'RP', type: 'number' },
      { key: 'mmr', label: 'MMR', type: 'number' },
      { key: 'wins', label: 'W', type: 'number' },
      { key: 'losses', label: 'L', type: 'number' },
      { key: 'draws', label: 'D', type: 'number' },
      { key: 'best_solo_score', label: 'Solo', type: 'number' },
      { key: 'total_matches', label: 'Матчи', type: 'number' },
    ],
  },
  rankTiers: {
    key: 'rankTiers',
    title: 'Таблица рангов',
    section: 'Рейтинг',
    path: '/rating/tiers',
    description: 'Справочник рангов: диапазоны rank_points, название, статус и картинка ранга.',
    editable: true,
    statusField: 'status',
    statusOptions: ['active', 'inactive'],
    filters: [{ label: 'Статус', key: 'status', options: ['active', 'inactive'] }],
    advancedFilters: [
      { key: 'tier_key', label: 'Ключ', type: 'text', placeholder: 'gold' },
      { key: 'status', label: 'Статус', type: 'select', options: ['active', 'inactive'] },
    ],
    editorFields: [
      { key: 'tier_key', label: 'Ключ ранга', type: 'text', required: true, placeholder: 'gold' },
      { key: 'label', label: 'Название EN', type: 'text', required: true, placeholder: 'Gold' },
      { key: 'label_ru', label: 'Название RU', type: 'text', placeholder: 'Золото' },
      { key: 'min_points', label: 'Очки от', type: 'number', required: true, defaultValue: 0 },
      { key: 'max_points', label: 'Очки до', type: 'number', placeholder: 'Пусто = без верхней границы' },
      { key: 'image_url', label: 'Картинка ранга', type: 'image', upload: true, placeholder: '/uploads/ranks/gold.webp' },
      { key: 'status', label: 'Статус', type: 'select', options: ['active', 'inactive'], defaultValue: 'active', required: true },
      { key: 'sort_order', label: 'Порядок', type: 'number', defaultValue: 0 },
    ],
    columns: [
      { key: 'image_url', label: 'Картинка', type: 'avatar', width: '86px' },
      { key: 'tier_key', label: 'Ключ', type: 'badge' },
      { key: 'label', label: 'Название EN' },
      { key: 'label_ru', label: 'Название RU' },
      { key: 'min_points', label: 'От', type: 'number' },
      { key: 'max_points', label: 'До', type: 'number' },
      { key: 'status', label: 'Статус', type: 'inlineStatus' },
      { key: 'sort_order', label: 'Порядок', type: 'number' },
      { key: 'updated_at', label: 'Обновлено', type: 'datetime' },
    ],
  },
  ratingHistory: {
    key: 'ratingHistory',
    title: 'История рейтинга',
    section: 'Рейтинг',
    path: '/rating/history',
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'user_id', label: 'User ID' },
      { key: 'match_id', label: 'Матч' },
      { key: 'rank_delta', label: 'RP delta', type: 'number' },
      { key: 'mmr_delta', label: 'MMR delta', type: 'number' },
      { key: 'reason', label: 'Причина', type: 'badge' },
      { key: 'created_at', label: 'Время', type: 'datetime' },
    ],
  },
  supportRequests: {
    key: 'supportRequests',
    title: 'Обращения',
    section: 'Поддержка',
    path: '/support/requests',
    filters: [
      { label: 'Категория', key: 'category', options: ['bug', 'idea', 'mode', 'balance', 'other'] },
      { label: 'Статус', key: 'status', options: ['new', 'triaged', 'in_progress', 'closed', 'spam'] },
      { label: 'Канал', key: 'preferred_channel', options: ['email', 'telegram'] },
    ],
    columns: [
      { key: 'id', label: 'ID', width: '72px', type: 'supportRequestLink' },
      { key: 'user_id', label: 'User ID', type: 'userLink' },
      { key: 'category', label: 'Категория', type: 'badge' },
      { key: 'status', label: 'Статус', type: 'badge' },
      { key: 'priority', label: 'Приоритет', type: 'badge' },
      { key: 'preferred_channel', label: 'Канал', type: 'badge' },
      { key: 'title', label: 'Тема' },
      { key: 'contact_email', label: 'Email' },
      { key: 'telegram_username', label: 'Telegram', type: 'telegram' },
      { key: 'telegram_linked_at', label: 'TG linked', type: 'datetime' },
      { key: 'created_at', label: 'Создано', type: 'datetime' },
    ],
  },
  supportBlocks: {
    key: 'supportBlocks',
    title: 'Блокировки обращений',
    section: 'Поддержка',
    path: '/support/blocks',
    editable: true,
    statusField: 'status',
    statusOptions: ['active', 'inactive'],
    filters: [{ label: 'Статус', key: 'status', options: ['active', 'inactive'] }],
    advancedFilters: [
      { key: 'user_id', label: 'User ID', type: 'number', placeholder: 'ID пользователя' },
      { key: 'status', label: 'Статус', type: 'select', options: ['active', 'inactive'] },
    ],
    editorFields: [
      { key: 'user_id', label: 'User ID', type: 'number', required: true, placeholder: '128' },
      { key: 'status', label: 'Статус', type: 'select', options: ['active', 'inactive'], defaultValue: 'active', required: true },
      { key: 'reason', label: 'Причина', type: 'text', placeholder: 'Спам, злоупотребление формой...' },
      { key: 'blocked_until', label: 'Блокировать до', type: 'datetime-local' },
      { key: 'blocked_by_user_id', label: 'Admin ID', type: 'number' },
    ],
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'user_id', label: 'User ID', type: 'userLink' },
      { key: 'username', label: 'Игрок', type: 'userNameLink' },
      { key: 'email', label: 'Email', type: 'userEmailLink' },
      { key: 'status', label: 'Статус', type: 'inlineStatus' },
      { key: 'reason', label: 'Причина', truncate: true },
      { key: 'blocked_until', label: 'До', type: 'datetime' },
      { key: 'updated_at', label: 'Обновлено', type: 'datetime' },
    ],
  },
  donations: {
    key: 'donations',
    title: 'Платежи',
    section: 'Донаты',
    path: '/donations',
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'donor_name', label: 'Донор' },
      { key: 'currency_code', label: 'Валюта', type: 'badge' },
      { key: 'network_key', label: 'Сеть' },
      { key: 'expected_amount', label: 'Ожидалось', type: 'number' },
      { key: 'amount_usd', label: 'USD', type: 'number' },
      { key: 'status', label: 'Статус', type: 'badge' },
      { key: 'created_at', label: 'Создан', type: 'datetime' },
    ],
  },
  donationCurrencies: {
    key: 'donationCurrencies',
    primaryKey: 'code',
    title: 'Валюты',
    section: 'Донаты',
    path: '/donations/currencies',
    description: 'Справочник валют для пожертвований: криптовалюты, стейблкоины, иконки и порядок показа.',
    filters: [{ label: 'Статус', key: 'status', options: ['active', 'inactive'] }],
    editable: true,
    statusField: 'status',
    statusOptions: ['active', 'inactive'],
    editorFields: [
      { key: 'code', label: 'Код', type: 'text', required: true, placeholder: 'USDT' },
      { key: 'name', label: 'Название', type: 'text', required: true, placeholder: 'Tether USD' },
      { key: 'symbol', label: 'Символ', type: 'text', placeholder: 'USDT' },
      { key: 'icon_symbol', label: 'Иконка', type: 'text', placeholder: '₮' },
      { key: 'icon_url', label: 'URL иконки', type: 'image', upload: true, placeholder: '/uploads/donations/currencies/usdt.svg' },
      { key: 'decimals', label: 'Decimals', type: 'number', defaultValue: 8 },
      { key: 'status', label: 'Статус', type: 'select', options: ['active', 'inactive'], defaultValue: 'active', required: true },
      { key: 'sort_order', label: 'Порядок', type: 'number', defaultValue: 0 },
    ],
    columns: [
      { key: 'icon_symbol', label: 'Иконка', width: '76px', type: 'iconSymbol' },
      { key: 'code', label: 'Код', width: '110px', type: 'badge' },
      { key: 'name', label: 'Название' },
      { key: 'symbol', label: 'Символ' },
      { key: 'decimals', label: 'Decimals', type: 'number' },
      { key: 'status', label: 'Статус', type: 'inlineStatus' },
      { key: 'sort_order', label: 'Порядок', type: 'number' },
      { key: 'updated_at', label: 'Обновлено', type: 'datetime' },
    ],
  },
  donationNetworks: {
    key: 'donationNetworks',
    primaryKey: 'key',
    title: 'Сети',
    section: 'Донаты',
    path: '/donations/networks',
    description: 'Справочник блокчейн-сетей: нативная валюта, chain id, explorer и доступность.',
    filters: [{ label: 'Статус', key: 'status', options: ['active', 'inactive'] }],
    editable: true,
    statusField: 'status',
    statusOptions: ['active', 'inactive'],
    editorFields: [
      { key: 'key', label: 'Ключ', type: 'text', required: true, placeholder: 'ethereum' },
      { key: 'name', label: 'Название', type: 'text', required: true, placeholder: 'Ethereum' },
      { key: 'native_currency_code', label: 'Нативная валюта', type: 'suggest', suggestionSource: 'donationCurrencies', suggestionValue: 'code', suggestionLabel: 'name', placeholder: 'ETH' },
      { key: 'chain_id', label: 'Chain ID', type: 'text', placeholder: '1' },
      { key: 'explorer_url', label: 'Explorer URL', type: 'text', placeholder: 'https://etherscan.io' },
      { key: 'icon_symbol', label: 'Иконка', type: 'text', placeholder: 'Ξ' },
      { key: 'icon_url', label: 'URL иконки', type: 'image', upload: true },
      { key: 'status', label: 'Статус', type: 'select', options: ['active', 'inactive'], defaultValue: 'active', required: true },
      { key: 'sort_order', label: 'Порядок', type: 'number', defaultValue: 0 },
    ],
    columns: [
      { key: 'icon_symbol', label: 'Иконка', width: '76px', type: 'iconSymbol' },
      { key: 'key', label: 'Ключ' },
      { key: 'name', label: 'Название' },
      { key: 'native_currency_code', label: 'Натив', type: 'badge' },
      { key: 'chain_id', label: 'Chain ID' },
      { key: 'status', label: 'Статус', type: 'inlineStatus' },
      { key: 'sort_order', label: 'Порядок', type: 'number' },
      { key: 'updated_at', label: 'Обновлено', type: 'datetime' },
    ],
  },
  donationCurrencyNetworks: {
    key: 'donationCurrencyNetworks',
    title: 'Валюты и сети',
    section: 'Донаты',
    path: '/donations/currency-networks',
    description: 'Связи, какие валюты можно принимать в каких сетях: стандарт токена, контракт, memo и подтверждения.',
    filters: [
      { label: 'Статус', key: 'status', options: ['active', 'inactive'] },
      { label: 'Приём', key: 'deposit_enabled', options: ['true', 'false'] },
    ],
    editable: true,
    statusField: 'status',
    statusOptions: ['active', 'inactive'],
    editorFields: [
      { key: 'currency_code', label: 'Валюта', type: 'suggest', suggestionSource: 'donationCurrencies', suggestionValue: 'code', suggestionLabel: 'name', required: true, placeholder: 'USDT' },
      { key: 'network_key', label: 'Сеть', type: 'suggest', suggestionSource: 'donationNetworks', suggestionValue: 'key', suggestionLabel: 'name', required: true, placeholder: 'tron' },
      { key: 'token_standard', label: 'Стандарт', type: 'text', placeholder: 'TRC20' },
      { key: 'contract_address', label: 'Контракт', type: 'text' },
      { key: 'min_confirmations', label: 'Подтверждения', type: 'number', defaultValue: 1 },
      { key: 'memo_required', label: 'Memo/tag обязателен', type: 'checkbox', defaultValue: false },
      { key: 'deposit_enabled', label: 'Приём включён', type: 'checkbox', defaultValue: true },
      { key: 'status', label: 'Статус', type: 'select', options: ['active', 'inactive'], defaultValue: 'active', required: true },
      { key: 'sort_order', label: 'Порядок', type: 'number', defaultValue: 0 },
    ],
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'currency_code', label: 'Валюта', type: 'badge' },
      { key: 'currency_name', label: 'Название' },
      { key: 'network_key', label: 'Сеть' },
      { key: 'network_name', label: 'Название сети' },
      { key: 'token_standard', label: 'Стандарт' },
      { key: 'min_confirmations', label: 'Conf', type: 'number' },
      { key: 'memo_required', label: 'Memo', type: 'boolean' },
      { key: 'deposit_enabled', label: 'Приём', type: 'boolean' },
      { key: 'status', label: 'Статус', type: 'inlineStatus' },
      { key: 'sort_order', label: 'Порядок', type: 'number' },
    ],
  },
  donationWallets: {
    key: 'donationWallets',
    title: 'Кошельки',
    section: 'Донаты',
    path: '/donations/wallets',
    editable: true,
    statusField: 'status',
    statusOptions: ['active', 'inactive', 'test'],
    editorFields: [
      { key: 'currency_network_id', label: 'Связь валюта-сеть', type: 'suggest', suggestionSource: 'donationCurrencyNetworks', suggestionValue: 'id', suggestionLabel: 'pairLabel', placeholder: 'USDT · TRON' },
      { key: 'currency_code', label: 'Валюта', type: 'suggest', suggestionSource: 'donationCurrencies', suggestionValue: 'code', suggestionLabel: 'name', required: true, placeholder: 'USDT' },
      { key: 'network_key', label: 'Сеть', type: 'suggest', suggestionSource: 'donationNetworks', suggestionValue: 'key', suggestionLabel: 'name', required: true, placeholder: 'tron' },
      { key: 'network_name', label: 'Название сети', type: 'text', required: true, placeholder: 'TRON' },
      { key: 'address', label: 'Адрес', type: 'text', required: true },
      { key: 'address_label', label: 'Подпись', type: 'text', placeholder: 'Основной кошелёк' },
      { key: 'memo_tag', label: 'Memo/tag', type: 'text' },
      { key: 'status', label: 'Статус', type: 'select', options: ['active', 'inactive', 'test'], defaultValue: 'active', required: true },
      { key: 'sort_order', label: 'Порядок', type: 'number', defaultValue: 0 },
    ],
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'currency_network_id', label: 'Связь' },
      { key: 'currency_code', label: 'Валюта', type: 'badge' },
      { key: 'network_name', label: 'Сеть' },
      { key: 'address', label: 'Адрес', truncate: true },
      { key: 'status', label: 'Статус', type: 'inlineStatus' },
      { key: 'sort_order', label: 'Порядок', type: 'number' },
      { key: 'updated_at', label: 'Обновлен', type: 'datetime' },
    ],
  },
  donationVerificationEvents: {
    key: 'donationVerificationEvents',
    title: 'Проверки транзакций',
    section: 'Донаты',
    path: '/donations/verification-events',
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'donation_id', label: 'Донат' },
      { key: 'event_type', label: 'Событие', type: 'badge' },
      { key: 'status_from', label: 'Было' },
      { key: 'status_to', label: 'Стало', type: 'badge' },
      { key: 'tx_hash', label: 'Tx', truncate: true },
      { key: 'created_at', label: 'Время', type: 'datetime' },
    ],
  },
  adminAudit: {
    key: 'adminAudit',
    title: 'Аудит админов',
    section: 'Система',
    path: '/system/audit',
    columns: [
      { key: 'id', label: 'ID', width: '72px' },
      { key: 'admin_user_id', label: 'Admin ID' },
      { key: 'action', label: 'Действие', type: 'badge' },
      { key: 'entity_type', label: 'Сущность' },
      { key: 'entity_id', label: 'Entity ID' },
      { key: 'created_at', label: 'Время', type: 'datetime' },
    ],
  },
  migrations: {
    key: 'migrations',
    title: 'Миграции',
    section: 'Система',
    path: '/system/migrations',
    columns: [
      { key: 'name', label: 'Файл миграции' },
      { key: 'applied_at', label: 'Применена', type: 'datetime' },
    ],
  },
}
